# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170804_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cid',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=100),
        ),
    ]
