# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170804_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cid',
            field=models.IntegerField(default=100),
        ),
    ]
